const {chromium}=require('playwright');
const {PDFDocument,rgb}=require('pdf-lib');
const fs=require('fs'),path=require('path'),assert=require('assert');
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1100},deviceScaleFactor:1});
 const errors=[];page.on('pageerror',e=>{errors.push(e.message);console.error('BROWSER',e.stack)});
 await page.addInitScript(()=>{const registered=[];Object.defineProperty(document,'modelContext',{value:{registerTool:tool=>registered.push(tool)},configurable:true});window.qaTools=registered;});
 page.on('console',m=>{if(m.type()==='error')console.error('CONSOLE',m.text())});await page.goto((process.argv[2]||'http://127.0.0.1:4173'),{waitUntil:'networkidle'});await page.screenshot({path:path.join(__dirname,'qa-desktop.png')});
 assert.equal(await page.locator('[data-check]').count(),50);
 await page.locator('[data-check="mattress"]').check();await page.reload();assert(await page.locator('[data-check="mattress"]').isChecked());
 await page.locator('[data-priority="arrival"]').click();assert(await page.locator('[data-check]').count()<50);
 await page.locator('#unfinished').check();assert.equal(await page.locator('[data-check="mattress"]').count(),0);
 await page.locator('[data-shop="sheets"]').click();assert.equal(await page.locator('#product-dialog a').count(),4);await page.locator('.dialog-close').click();
 await page.locator('[data-priority="all"]').click();await page.locator('#unfinished').uncheck();
 await page.locator('[data-store="Amazon"]').click();assert.equal(await page.locator('.product-card').count(),2);await page.locator('[data-product="bedsure"]').click();assert(await page.locator('#product-detail').innerText().then(t=>t.includes('不含枕芯')));await page.locator('.dialog-close').click();
 const registration=await page.evaluate(()=>window.qaTools.map(t=>({name:t.name,annotations:t.annotations,inputSchema:t.inputSchema})));assert.equal(registration.length,2);
 await page.evaluate(()=>window.qaTools.find(t=>t.name==='set_checklist_items').execute({items:[{id:'pillow',done:true}]}));assert(await page.locator('[data-check="pillow"]').isChecked());
 const before=await page.evaluate(()=>localStorage.getItem('settlein-v1'));const rejected=await page.evaluate(async()=>{try{await window.qaTools.find(t=>t.name==='set_checklist_items').execute({items:[{id:'no-such-item',done:true}]});return false}catch{return true}});assert(rejected);assert.equal(await page.evaluate(()=>localStorage.getItem('settlein-v1')),before);
 await page.locator('#customize-tab').click();await page.locator('#room-width').fill('3');await page.locator('#room-length').fill('3.6');await page.locator('#room-form button[type=submit]').click();assert((await page.locator('#room-results').innerText()).includes('Twin'));
 await page.locator('#person-height').fill('195');await page.locator('#room-form button[type=submit]').click();assert((await page.locator('.recommendation').first().innerText()).includes('Twin XL'));
 await page.locator('#room-width').fill('1');await page.locator('#room-length').fill('1');await page.locator('#room-form button[type=submit]').click();assert((await page.locator('.recommendation').first().innerText()).includes('目前空間不足'));
 await page.locator('#room-width').fill('0.5');await page.locator('#room-form button[type=submit]').click();assert((await page.locator('#room-error').innerText()).includes('1–20'));
 await page.locator('#room-width').fill('3');await page.locator('#room-length').fill('3.6');await page.locator('#dimension-unit').selectOption('cm');assert.equal(await page.locator('#room-width').inputValue(),'300');await page.locator('#dimension-unit').selectOption('m');assert.equal(await page.locator('#room-width').inputValue(),'3');
 // A known rectangular plan exercises PDF decoding, calibration, then measured recommendations.
 const pdf=await PDFDocument.create();const p=pdf.addPage([600,500]);p.drawRectangle({x:50,y:50,width:400,height:350,borderWidth:3,borderColor:rgb(0,0,0)});const fixture=path.join(__dirname,'qa-floor.pdf');fs.writeFileSync(fixture,await pdf.save());
 await page.locator('#floor-file').setInputFiles(fixture);await page.locator('#loaded-plan').waitFor({state:'visible',timeout:20000});await page.locator('#floor-image').evaluate(img=>img.decode());
 await page.locator('#plan-canvas').scrollIntoViewIfNeeded();const box=await page.locator('#plan-canvas').boundingBox();
 await page.mouse.click(box.x+box.width*.1,box.y+box.height*.1);await page.mouse.click(box.x+box.width*.9,box.y+box.height*.1);await page.locator('#reference-length').fill('4');await page.locator('#apply-scale').click();
 const box2=await page.locator('#plan-canvas').boundingBox();await page.mouse.click(box2.x+box2.width*.1,box2.y+box2.height*.1);await page.mouse.click(box2.x+box2.width*.9,box2.y+box2.height*.82);
 assert(Math.abs(Number(await page.locator('#room-width').inputValue())-4)<.05);assert(Math.abs(Number(await page.locator('#room-length').inputValue())-3)<.05);
 await page.locator('#room-form button[type=submit]').click();assert((await page.locator('#room-results').innerText()).includes('尺寸來自你標定'));
 await page.screenshot({path:path.join(__dirname,'qa-customize.png'),fullPage:true});
 await page.locator('[data-room="kitchen"]').click();await page.getByRole('heading',{name:'廚房的空間條件'}).waitFor();await page.locator('#room-width').fill('2.5');await page.locator('#room-length').fill('3');await page.locator('#room-form button[type=submit]').click();assert((await page.locator('#room-results').innerText()).includes('鍋具相容性'));
 await page.locator('#remove-image').click();assert(await page.locator('#dropzone').isVisible());
 await page.locator('#floor-file').setInputFiles({name:'bad.txt',mimeType:'text/plain',buffer:Buffer.from('not a plan')});assert((await page.locator('#upload-error').innerText()).includes('請使用'));
 await page.setViewportSize({width:390,height:844});await page.goto((process.argv[2]||'http://127.0.0.1:4173')+'/#general/bedroom');await page.screenshot({path:path.join(__dirname,'qa-mobile.png'),fullPage:true});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 await page.locator('#customize-tab').click();await page.locator('#room-width').waitFor();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 const images=await page.evaluate(()=>[...document.images].filter(i=>i.src.startsWith('https://')).map(i=>({src:i.src,loaded:i.complete&&i.naturalWidth>0})));
 console.log(JSON.stringify({checks:'50-item checklist; persistence; priority filters; merchant links; product modal; WebMCP adapter valid/invalid; room fit; tall sleeper; impossible fit; units; PDF upload; calibration; room selection; invalid upload; mobile overflow',images,errors,webmcp:'registration and execution tested with proposed API adapter; native WebMCP browser context unavailable'},null,2));assert.equal(errors.length,0);
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
