const {chromium}=require('playwright');
const assert=require('assert'),path=require('path');
const base=process.argv[2]||'http://127.0.0.1:4173';
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>{errors.push(e.message);console.error(e.message)});
 async function english(){assert.equal(await page.locator('html').getAttribute('lang'),'en');const text=await page.locator('body').innerText();assert(!/[\u3400-\u9fff]/.test(text.replaceAll('繁體中文','')),`Untranslated text: ${text.match(/.{0,30}[\u3400-\u9fff].{0,30}/g)}`)}
 await page.goto(base+'/en/',{waitUntil:'networkidle'});assert.equal(await page.locator('[data-check]').count(),50);await english();
 await page.locator('[data-check="mattress"]').check();await page.locator('#budget').fill('2000');await page.locator('#budget').blur();
 await page.locator('#language').selectOption('zh');await page.waitForURL(base+'/');await page.locator('[data-check="mattress"]').waitFor();assert(await page.locator('[data-check="mattress"]').isChecked());assert.equal(await page.locator('#budget').inputValue(),'2000');
 await page.locator('a.nav-item[href="#general/study"]').click();await page.locator('#language').selectOption('en');await page.waitForURL(base+'/en/#general/study');await page.locator('[data-check="desk"]').waitFor();await english();assert.equal(await page.locator('#budget').inputValue(),'2000');
 for(const room of ['all','bedroom','bathroom','kitchen','living','study','laundry']){await page.goto(base+'/en/#general/'+room);await page.locator('#room-title').waitFor();await english()}
 await page.goto(base+'/en/#general/all');await page.locator('[data-shop="sheets"]').click();await english();assert.equal(await page.locator('#product-dialog a').count(),4);await page.locator('.dialog-close').click();
 for(const store of ['IKEA','Target','Walmart','Amazon']){await page.locator(`[data-store="${store}"]`).click();const ids=await page.locator('[data-product]').evaluateAll(nodes=>nodes.map(n=>n.dataset.product));for(const id of ids){await page.locator(`[data-product="${id}"]`).click();await english();await page.locator('.dialog-close').click()}}
 await page.locator('[data-store="all"]').click();await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(__dirname,'qa-en-desktop.png')});
 await page.locator('#customize-tab').click();await page.locator('#room-width').fill('3');await page.locator('#room-length').fill('3.6');await page.locator('#room-form button[type=submit]').click();await english();assert((await page.locator('#room-results').innerText()).includes('Twin'));
 await page.locator('#room-width').fill('0.5');await page.locator('#room-form button[type=submit]').click();assert((await page.locator('#room-error').innerText()).includes('between 1 and 20'));
 await page.locator('#floor-file').setInputFiles(path.join(__dirname,'qa-floor.pdf'));await page.locator('#loaded-plan').waitFor({state:'visible'});await page.locator('#floor-image').evaluate(img=>img.decode());await english();
 await page.locator('#plan-canvas').scrollIntoViewIfNeeded();const box=await page.locator('#plan-canvas').boundingBox();await page.mouse.click(box.x+box.width*.1,box.y+box.height*.1);await page.mouse.click(box.x+box.width*.9,box.y+box.height*.1);await page.locator('#reference-length').fill('4');await page.locator('#apply-scale').click();await english();const b=await page.locator('#plan-canvas').boundingBox();await page.mouse.click(b.x+b.width*.1,b.y+b.height*.1);await page.mouse.click(b.x+b.width*.9,b.y+b.height*.82);await page.locator('#room-form button[type=submit]').click();await english();assert((await page.locator('#room-results').innerText()).includes('calibrated floor plan'));
 for(const room of ['bathroom','kitchen','living','study','laundry']){await page.locator(`[data-room="${room}"]`).click();await page.waitForFunction(r=>document.querySelector('.room-saved button.active')?.dataset.room===r,room);await page.locator('#room-width').fill('3');await page.locator('#room-length').fill('4');await page.locator('#room-form button[type=submit]').click();await english()}
 await page.locator('#language').selectOption('zh');await page.waitForURL(base+'/#customize/laundry');await page.getByRole('heading',{name:'洗衣與日用的空間條件'}).waitFor();assert.equal(await page.locator('#room-width').inputValue(),'3');
 await page.setViewportSize({width:390,height:844});await page.goto(base+'/en/#general/bedroom');await page.locator('[data-check="mattress"]').waitFor();await page.screenshot({path:path.join(__dirname,'qa-en-mobile.png')});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 await page.locator('#customize-tab').click();await page.locator('#room-width').waitFor();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 assert.equal(errors.length,0);console.log('PASS: full English UI; 50 items; all room tabs; 10 product dialogs; language switch retains route, checklist, budget and room plans; English PDF upload, calibration, validation and recommendations; mobile overflow; no browser errors.');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
